version: '2.0'

services:
  node1.oneprovider:
    image: onedata/oneprovider:18.02.0-beta1
    hostname: node1.oneprovider.
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "/opt/oneprovider/persistence:/volumes/persistence"
        # data persistence
        - "/opt/oneprovider/storage:/volumes/storage"
        # Server SSL certificates
        #- "/etc/letsencrypt/live/${FQDN}/privkey.pem:/etc/op_panel/certs/web_key.pem"
        #- "/etc/letsencrypt/live/${FQDN}/cert.pem:/etc/op_panel/certs/web_cert.pem"
        #- "/etc/letsencrypt/live/${FQDN}/chain.pem:/etc/op_panel/certs/web_chain.pem"
    ports:
      - "80:80"
      - "443:443"
      - "6665:6665"
      - "9443:9443"
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_LOG_LEVEL: "none" # prints logs to stdout (possible values: none, debug, info, error), by default set to info
      ONEPANEL_GENERATE_TEST_WEB_CERT: "true"  # default: false
      ONEPANEL_GENERATED_CERT_DOMAIN: "node1.oneprovider"  # default: ""
      ONEPANEL_TRUST_TEST_CA: "true"  # default: false
      ONEPROVIDER_CONFIG: |
        cluster:
          domainName: "oneprovider."
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
          storages:
            LocalDisk:
              type: "posix"
              mountPoint: "/volumes/storage"
        oneprovider:
          register: true
          name: "${PROVIDER_NAME}"
          subdomainDelegation: false
          domain: "${FQDN}" # OR IP ADDRESS
          adminEmail: "bkryza@gmail.com"
          geoLatitude: ${GEO_LATITUDE}
          geoLongitude: ${GEO_LONGITUDE}
        onezone:
          domainName: "${ZONE_FQDN}" # OR IP ADDRESS
        onepanel:
          users:
            "admin":
              password: "${ADMIN_PASSWORD}"
              userRole: "admin"
