version: '2.0'

services:
  node1.oneprovider:
    image: onedata/oneprovider:18.02.0-beta1
    hostname: node1.oneprovider.
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "/opt/oneprovider/persistence:/volumes/persistence"
        # data persistence
        - "/opt/oneprovider/storage:/volumes/storage"
        # Server SSL certificates
        - "/etc/letsencrypt/live/${FQDN}/privkey.pem:/etc/op_panel/certs/web_key.pem"
        - "/etc/letsencrypt/live/${FQDN}/cert.pem:/etc/op_panel/certs/web_cert.pem"
        - "/etc/letsencrypt/live/${FQDN}/chain.pem:/etc/op_panel/certs/web_chain.pem"
        # Additional, trusted CA certificates (any filename is accepted)
        #- "${OP_CACERTS_PATH}:/etc/op_panel/cacerts/customCaBundle.pem"
    ports:
      - "80:80"
      - "443:443"
      - "6665:6665"
      - "9443:9443"
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_LOG_LEVEL: "none" # prints logs to stdout (possible values: none, debug, info, error), by default set to info
      ONEPROVIDER_CONFIG: |
        cluster:
          domainName: "oneprovider."
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
          storages:
            NFS:
              type: "posix"
              mountPoint: "/volumes/storage"
        oneprovider:
          register: true
          name: "${PROVIDER_NAME}"

          # "false" in subdomainDelegation means that provider admin
          #         manages its DNS on its own and provider is available
          #         under the domain given in "domain" field
          # "true" means provider is using a subdomain given in "subdomain"
          #        config field which is registered under the onezone domain
          #        given in a config in the onezone domain
          # Note that for subdomainDelegation "true" to work onezone with
          # properly configured DNS zone delegation and external IP is needed.
          # This onezone setup is not covered by the getting-started scenarios.
          subdomainDelegation: false
          domain: "${FQDN}" # OR IP ADDRESS
          adminEmail: "bkryza@gmail.com"
          geoLatitude: ${GEO_LATITUDE}
          geoLongitude: ${GEO_LONGITUDE}
        onezone:
          domainName: "${ZONE_FQDN}" # OR IP ADDRESS
        onepanel:
          users:
            "admin":
              password: "password"
              userRole: "admin"
            "user":
              password: "password"
              userRole: "regular"
